FROM golang:latest

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY keyvaluestore keyvaluestore

COPY server server

RUN go build -o bin/server server/main.go

ENTRYPOINT [ "./bin/server" ]